/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Hakuru15 (https://sketchfab.com/Hakuru15)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/desk-f4f28afa50494426b5c3992c1b73a83b
title: Desk
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/desk.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.DefaultMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/desk.glb");
